#!/usr/bin/env bash

# dialog/progress variables
export local showdialog="yad --title "sisyphus" --text-info --width 800 --height 600 --center --no-buttons --on-top --sticky --fixed --skip-taskbar --listen --tail &"
export local showprogress="yad --title "sisyphus" --progress --pulsate --width 800 --center --no-buttons --on-top --sticky --fixed --undecorated --skip-taskbar  --auto-close &"

# main ui functions 
export local mainwindow='
<window title="Sisyphus - A simple Epkg GUI" window-position="1" icon-name="gtk-search" modal="true" resizable="false" width-request="800" height-request="600">
<vbox>
<frame Manage Packages>
	<hbox>
		<text>
			<label>Enter package(s)</label>
		</text>
		<entry>
			<variable>pkgname</variable>
		</entry>
	</hbox>
	<hbox>
		<button tooltip-text="Search for package(s)">
			<label>Search package(s)</label>
			<action>epkg search $pkgname | $showdialog</action>
		</button>
		<button tooltip-text="Install new package(s) (no confirmation)">
			<label>Install package(s)</label>
			<action>epkg autoinstall $pkgname | $showdialog</action>
		</button>
		<button tooltip-text="Uninstall package(s) safely (no confirmation)">
			<label>Remove package(s)</label>
			<action>epkg autoremove $pkgname | $showdialog</action>
		</button>
		<button tooltip-text="Upgrade system (no confirmation)">
			<label>Upgrade System</label>
			<action>epkg autoupgrade | $showdialog</action>
		</button>
		<button tooltip-text="Remove orphan packages(s) aka no longer needed (no confirmation)">
			<label>Remove orphan package(s)</label>
			<action>epkg autoclean | $showdialog</action>
		</button>
	</hbox>
</frame>
<frame Browse Packages>
	<hbox>
		<button tooltip-text="Accesories">
			<label>Accesories</label>
		</button>
		<button tooltip-text="Games">
			<label>Games</label>
		</button>
		<button tooltip-text="Graphics">
			<label>Graphics</label>
		</button>
		<button tooltip-text="Internet">
			<label>Internet</label>
		</button>	
	</hbox>
	<hbox>
		<button tooltip-text="Sound & Video">
			<label>Sound & Video</label>
		</button>
		<button tooltip-text="Office">
			<label>Office</label>
		</button>
		<button tooltip-text="System Tools">
			<label>System Tools</label>
		</button>
	</hbox>
</frame>
<frame Terminal Emulator>
	<hbox>
		<terminal argv0="/bin/bash">
			<variable>vte1</variable>
			<input>echo epkg</input>
		</terminal>
	</hbox>
</frame>
</vbox>
</window>
'
