#!/usr/bin/env bash

# Sisyphus is a simple GUI for epkg, the portage wrapper
# It uses gnome-extra/yad, x11-libs/vte && x11-misc/gtkdialog
# Main Author : Ghiunhan Mamut @ Redcore Linux Project

# import main user interface
source libsisyphus.sh

main() {
	gtkdialog --space-expand=true --space-fill=true --program=mainui &
}

main
