#!/usr/bin/env bash

# Sisyphus is a simple GUI for sisyphus, the portage wrapper
# Main Author : Ghiunhan Mamut @ Redcore Linux Project

main() {
	pushd /usr/share/sisyphus
	python3 sisyphus-gui.py
	popd
}

main
