#!/usr/bin/env bash

# Sisyphus is a simple GUI for epkg, the portage wrapper
# It uses gnome-extra/yad, x11-libs/vte && x11-misc/gtkdialog
# Main Author : Ghiunhan Mamut @ RogentOS Development Group

export local showprogress="yad --title "sisyphus" --text-info --width 640 --height 480 --center --no-buttons --on-top --sticky --fixed --undecorated --skip-taskbar --listen --tail &"
export local SISYPHUS='
<window title="Sisyphus - A simple Epkg GUI" window-position="1" icon-name="gtk-search" modal="true" resizable="false" width-request="1000" height-request="600">
<vbox>
<frame Manage Packages>
	<hbox>
		<text>
			<label>Enter package(s)</label>
		</text>
		<entry>
			<variable>pkgname</variable>
		</entry>
	</hbox>
	<hbox>
		<button tooltip-text="Install new package(s) (no confirmation)">
			<label>Install package(s)</label>
			<action>epkg autoinstall $pkgname | $showprogress</action>
		</button>
		<button tooltip-text="Search for package(s)">
			<label>Search package(s)</label>
			<action>epkg search $pkgname | $showprogress</action>
		</button>
		<button tooltip-text="Uninstall package(s) safely (no confirmation)">
			<label>Remove package(s)</label>
			<action>epkg autoremove $pkgname | $showprogress</action>
		</button>
		<button tooltip-text="Remove orphan packages(s) aka no longer needed (no confirmation)">
			<label>Remove orphan package(s)</label>
			<action>epkg autoclean | $showprogress</action>
		</button>
	</hbox>
	<hbox>
		<button tooltip-text="Update portage tree, portage configs && Kogaion overlay">
			<label>Update Database</label>
			<action>epkg update | $showprogress</action>
		</button>
		<button tooltip-text="Upgrade system (no confirmation)">
			<label>Upgrade System</label>
			<action>epkg autoupgrade | $showprogress </action>
		</button>
		<button tooltip-text="Display information about installed core packages and portage configuration">
			<label>Portage Information</label>
			<action>epkg sysinfo | $showprogress</action>
		</button>
	</hbox>
</frame>
<frame Terminal Emulator>
	<hbox>
		<terminal argv0="/bin/bash">
			<variable>vte1</variable>
			<input>echo epkg</input>
		</terminal>
	</hbox>
</frame>
<frame Exit>
	<hbox>
		<button>
			<label>Exit</label>
			<action>EXIT:ok</action>
		</button>
	</hbox>
</frame>
</vbox>
</window>
'

gtkdialog --space-expand=true --space-fill=true --program=SISYPHUS
