#!/usr/bin/env bash

collect_local_portage_database() {
	for i in $(sed -e "s/\:1.0//g" </var/lib/portage/world); do
		pushd /var/db/pkg/"$i"* > /dev/null 2>&1
		echo "$(<CATEGORY),$(sed -re "s/-([0-9])/,\1/" <PF),$(<SLOT),$(sed -e "s/\"//g" -e "s/\'//g" -e "s/\,//g" <DESCRIPTION)" >> /tmp/spmsync.csv
		popd > /dev/null 2>&1
	done
	mv /tmp/spmsync.csv /var/lib/sisyphus/csv/
}

clean_temporary_files() {
	rm -rf /tmp/spmsync.csv
}

main() {
	collect_local_portage_database
	clean_temporary_files
}

main
